BEGIN;

SET search_path TO tarot, public;

INSERT INTO tarot_archetypes (
  code,
  system_code,
  name_zh,
  name_en,
  arcana_type,
  major_number,
  suit_code,
  rank_code,
  rank_order,
  sequence_no
)
VALUES
  ('major-00', 'rws-78', '愚者', 'The Fool', 'major', 0, NULL, NULL, NULL, 0),
  ('major-01', 'rws-78', '魔术师', 'The Magician', 'major', 1, NULL, NULL, NULL, 1),
  ('major-02', 'rws-78', '女祭司', 'The High Priestess', 'major', 2, NULL, NULL, NULL, 2),
  ('major-03', 'rws-78', '皇后', 'The Empress', 'major', 3, NULL, NULL, NULL, 3),
  ('major-04', 'rws-78', '皇帝', 'The Emperor', 'major', 4, NULL, NULL, NULL, 4),
  ('major-05', 'rws-78', '教皇', 'The Hierophant', 'major', 5, NULL, NULL, NULL, 5),
  ('major-06', 'rws-78', '恋人', 'The Lovers', 'major', 6, NULL, NULL, NULL, 6),
  ('major-07', 'rws-78', '战车', 'The Chariot', 'major', 7, NULL, NULL, NULL, 7),
  ('major-08', 'rws-78', '力量', 'Strength', 'major', 8, NULL, NULL, NULL, 8),
  ('major-09', 'rws-78', '隐士', 'The Hermit', 'major', 9, NULL, NULL, NULL, 9),
  ('major-10', 'rws-78', '命运之轮', 'Wheel of Fortune', 'major', 10, NULL, NULL, NULL, 10),
  ('major-11', 'rws-78', '正义', 'Justice', 'major', 11, NULL, NULL, NULL, 11),
  ('major-12', 'rws-78', '倒吊人', 'The Hanged Man', 'major', 12, NULL, NULL, NULL, 12),
  ('major-13', 'rws-78', '死神', 'Death', 'major', 13, NULL, NULL, NULL, 13),
  ('major-14', 'rws-78', '节制', 'Temperance', 'major', 14, NULL, NULL, NULL, 14),
  ('major-15', 'rws-78', '恶魔', 'The Devil', 'major', 15, NULL, NULL, NULL, 15),
  ('major-16', 'rws-78', '高塔', 'The Tower', 'major', 16, NULL, NULL, NULL, 16),
  ('major-17', 'rws-78', '星星', 'The Star', 'major', 17, NULL, NULL, NULL, 17),
  ('major-18', 'rws-78', '月亮', 'The Moon', 'major', 18, NULL, NULL, NULL, 18),
  ('major-19', 'rws-78', '太阳', 'The Sun', 'major', 19, NULL, NULL, NULL, 19),
  ('major-20', 'rws-78', '审判', 'Judgement', 'major', 20, NULL, NULL, NULL, 20),
  ('major-21', 'rws-78', '世界', 'The World', 'major', 21, NULL, NULL, NULL, 21),
  ('minor-wands-ace', 'rws-78', '权杖王牌', 'Ace of Wands', 'minor', NULL, 'wands', 'ace', 1, 22),
  ('minor-wands-two', 'rws-78', '权杖二', 'Two of Wands', 'minor', NULL, 'wands', 'two', 2, 23),
  ('minor-wands-three', 'rws-78', '权杖三', 'Three of Wands', 'minor', NULL, 'wands', 'three', 3, 24),
  ('minor-wands-four', 'rws-78', '权杖四', 'Four of Wands', 'minor', NULL, 'wands', 'four', 4, 25),
  ('minor-wands-five', 'rws-78', '权杖五', 'Five of Wands', 'minor', NULL, 'wands', 'five', 5, 26),
  ('minor-wands-six', 'rws-78', '权杖六', 'Six of Wands', 'minor', NULL, 'wands', 'six', 6, 27),
  ('minor-wands-seven', 'rws-78', '权杖七', 'Seven of Wands', 'minor', NULL, 'wands', 'seven', 7, 28),
  ('minor-wands-eight', 'rws-78', '权杖八', 'Eight of Wands', 'minor', NULL, 'wands', 'eight', 8, 29),
  ('minor-wands-nine', 'rws-78', '权杖九', 'Nine of Wands', 'minor', NULL, 'wands', 'nine', 9, 30),
  ('minor-wands-ten', 'rws-78', '权杖十', 'Ten of Wands', 'minor', NULL, 'wands', 'ten', 10, 31),
  ('minor-wands-page', 'rws-78', '权杖侍从', 'Page of Wands', 'minor', NULL, 'wands', 'page', 11, 32),
  ('minor-wands-knight', 'rws-78', '权杖骑士', 'Knight of Wands', 'minor', NULL, 'wands', 'knight', 12, 33),
  ('minor-wands-queen', 'rws-78', '权杖王后', 'Queen of Wands', 'minor', NULL, 'wands', 'queen', 13, 34),
  ('minor-wands-king', 'rws-78', '权杖国王', 'King of Wands', 'minor', NULL, 'wands', 'king', 14, 35),
  ('minor-cups-ace', 'rws-78', '圣杯王牌', 'Ace of Cups', 'minor', NULL, 'cups', 'ace', 1, 36),
  ('minor-cups-two', 'rws-78', '圣杯二', 'Two of Cups', 'minor', NULL, 'cups', 'two', 2, 37),
  ('minor-cups-three', 'rws-78', '圣杯三', 'Three of Cups', 'minor', NULL, 'cups', 'three', 3, 38),
  ('minor-cups-four', 'rws-78', '圣杯四', 'Four of Cups', 'minor', NULL, 'cups', 'four', 4, 39),
  ('minor-cups-five', 'rws-78', '圣杯五', 'Five of Cups', 'minor', NULL, 'cups', 'five', 5, 40),
  ('minor-cups-six', 'rws-78', '圣杯六', 'Six of Cups', 'minor', NULL, 'cups', 'six', 6, 41),
  ('minor-cups-seven', 'rws-78', '圣杯七', 'Seven of Cups', 'minor', NULL, 'cups', 'seven', 7, 42),
  ('minor-cups-eight', 'rws-78', '圣杯八', 'Eight of Cups', 'minor', NULL, 'cups', 'eight', 8, 43),
  ('minor-cups-nine', 'rws-78', '圣杯九', 'Nine of Cups', 'minor', NULL, 'cups', 'nine', 9, 44),
  ('minor-cups-ten', 'rws-78', '圣杯十', 'Ten of Cups', 'minor', NULL, 'cups', 'ten', 10, 45),
  ('minor-cups-page', 'rws-78', '圣杯侍从', 'Page of Cups', 'minor', NULL, 'cups', 'page', 11, 46),
  ('minor-cups-knight', 'rws-78', '圣杯骑士', 'Knight of Cups', 'minor', NULL, 'cups', 'knight', 12, 47),
  ('minor-cups-queen', 'rws-78', '圣杯王后', 'Queen of Cups', 'minor', NULL, 'cups', 'queen', 13, 48),
  ('minor-cups-king', 'rws-78', '圣杯国王', 'King of Cups', 'minor', NULL, 'cups', 'king', 14, 49),
  ('minor-swords-ace', 'rws-78', '宝剑王牌', 'Ace of Swords', 'minor', NULL, 'swords', 'ace', 1, 50),
  ('minor-swords-two', 'rws-78', '宝剑二', 'Two of Swords', 'minor', NULL, 'swords', 'two', 2, 51),
  ('minor-swords-three', 'rws-78', '宝剑三', 'Three of Swords', 'minor', NULL, 'swords', 'three', 3, 52),
  ('minor-swords-four', 'rws-78', '宝剑四', 'Four of Swords', 'minor', NULL, 'swords', 'four', 4, 53),
  ('minor-swords-five', 'rws-78', '宝剑五', 'Five of Swords', 'minor', NULL, 'swords', 'five', 5, 54),
  ('minor-swords-six', 'rws-78', '宝剑六', 'Six of Swords', 'minor', NULL, 'swords', 'six', 6, 55),
  ('minor-swords-seven', 'rws-78', '宝剑七', 'Seven of Swords', 'minor', NULL, 'swords', 'seven', 7, 56),
  ('minor-swords-eight', 'rws-78', '宝剑八', 'Eight of Swords', 'minor', NULL, 'swords', 'eight', 8, 57),
  ('minor-swords-nine', 'rws-78', '宝剑九', 'Nine of Swords', 'minor', NULL, 'swords', 'nine', 9, 58),
  ('minor-swords-ten', 'rws-78', '宝剑十', 'Ten of Swords', 'minor', NULL, 'swords', 'ten', 10, 59),
  ('minor-swords-page', 'rws-78', '宝剑侍从', 'Page of Swords', 'minor', NULL, 'swords', 'page', 11, 60),
  ('minor-swords-knight', 'rws-78', '宝剑骑士', 'Knight of Swords', 'minor', NULL, 'swords', 'knight', 12, 61),
  ('minor-swords-queen', 'rws-78', '宝剑王后', 'Queen of Swords', 'minor', NULL, 'swords', 'queen', 13, 62),
  ('minor-swords-king', 'rws-78', '宝剑国王', 'King of Swords', 'minor', NULL, 'swords', 'king', 14, 63),
  ('minor-pentacles-ace', 'rws-78', '星币王牌', 'Ace of Pentacles', 'minor', NULL, 'pentacles', 'ace', 1, 64),
  ('minor-pentacles-two', 'rws-78', '星币二', 'Two of Pentacles', 'minor', NULL, 'pentacles', 'two', 2, 65),
  ('minor-pentacles-three', 'rws-78', '星币三', 'Three of Pentacles', 'minor', NULL, 'pentacles', 'three', 3, 66),
  ('minor-pentacles-four', 'rws-78', '星币四', 'Four of Pentacles', 'minor', NULL, 'pentacles', 'four', 4, 67),
  ('minor-pentacles-five', 'rws-78', '星币五', 'Five of Pentacles', 'minor', NULL, 'pentacles', 'five', 5, 68),
  ('minor-pentacles-six', 'rws-78', '星币六', 'Six of Pentacles', 'minor', NULL, 'pentacles', 'six', 6, 69),
  ('minor-pentacles-seven', 'rws-78', '星币七', 'Seven of Pentacles', 'minor', NULL, 'pentacles', 'seven', 7, 70),
  ('minor-pentacles-eight', 'rws-78', '星币八', 'Eight of Pentacles', 'minor', NULL, 'pentacles', 'eight', 8, 71),
  ('minor-pentacles-nine', 'rws-78', '星币九', 'Nine of Pentacles', 'minor', NULL, 'pentacles', 'nine', 9, 72),
  ('minor-pentacles-ten', 'rws-78', '星币十', 'Ten of Pentacles', 'minor', NULL, 'pentacles', 'ten', 10, 73),
  ('minor-pentacles-page', 'rws-78', '星币侍从', 'Page of Pentacles', 'minor', NULL, 'pentacles', 'page', 11, 74),
  ('minor-pentacles-knight', 'rws-78', '星币骑士', 'Knight of Pentacles', 'minor', NULL, 'pentacles', 'knight', 12, 75),
  ('minor-pentacles-queen', 'rws-78', '星币王后', 'Queen of Pentacles', 'minor', NULL, 'pentacles', 'queen', 13, 76),
  ('minor-pentacles-king', 'rws-78', '星币国王', 'King of Pentacles', 'minor', NULL, 'pentacles', 'king', 14, 77)
ON CONFLICT (code) DO UPDATE
SET
  system_code = EXCLUDED.system_code,
  name_zh = EXCLUDED.name_zh,
  name_en = EXCLUDED.name_en,
  arcana_type = EXCLUDED.arcana_type,
  major_number = EXCLUDED.major_number,
  suit_code = EXCLUDED.suit_code,
  rank_code = EXCLUDED.rank_code,
  rank_order = EXCLUDED.rank_order,
  sequence_no = EXCLUDED.sequence_no;

COMMIT;
